benchmarks:
  input_size: 1346 #input size in bytes
  output_size: 32
  client_poll_threads: 1
  client_connections: 16
  client_threads: 16
  rate: 4000000
  server_duration: 150 #server_duration in seconds
  client_duration: 150
  client_batch_size: 32
  server_address: "172.19.0.121:8501"
  server_poll_threads: 1
  experiment: "mc_tput_16"
  core_affinity: [49, 65]
